export enum EventTypeLog {
  USER_CONNECTED = "USER_CONNECTED",
  USER_DISCONNECTED = "USER_DISCONNECTED",
  AMBULANCE_CONNECTED = "AMBULANCE_CONNECTED",
  AMBULANCE_DISCONNECTED = "AMBULANCE_DISCONNECTED",
  EMERGENCY_CREATED = "EMERGENCY_CREATED",
  EMERGENCY_PENDING = "EMERGENCY_PENDING",
  EMERGENCY_ACCEPTED = "EMERGENCY_ACCEPTED",
  EMERGENCY_DISPATCHED = "EMERGENCY_DISPATCHED",
  EMERGENCY_ARRIVED = "EMERGENCY_ARRIVED",
  EMERGENCY_DURING_TRANSFER = "EMERGENCY_DURING_TRANSFER",
  EMERGENCY_FINALIZED = "EMERGENCY_FINALIZED",
  EMERGENCY_CANCELED = "EMERGENCY_CANCELED",
  EMERGENCY_STATE_CHANGED = "EMERGENCY_STATE_CHANGED",
  USER_CREATED = "USER_CREATED",
  USER_DELETED = "USER_DELETED",
  USER_CHANGED = "USER_CHANGED",
  CENTER_CREATED = "CENTER_CREATED",
  CENTER_DELETED = "CENTER_DELETED",
  CENTER_CHANGED = "CENTER_CHANGED",
}

export enum EstadoEmergencia {
  CREATED = "CREATED",
  PENDIENTE = "PENDIENTE",
  DESPACHADA = "DESPACHADA",
  EN_CAMINO = "EN_CAMINO",
  EN_SITIO = "EN_SITIO",
  EN_TRASLADO = "EN_TRASLADO",
  FINALIZADA = "FINALIZADA",
  CANCELADA = "CANCELADA",
}

export const configEvent: Record<EstadoEmergencia, EventTypeLog> = {
  CREATED: EventTypeLog.EMERGENCY_CREATED,
  PENDIENTE: EventTypeLog.EMERGENCY_PENDING,
  DESPACHADA: EventTypeLog.EMERGENCY_ACCEPTED,
  EN_CAMINO: EventTypeLog.EMERGENCY_DISPATCHED,
  EN_SITIO: EventTypeLog.EMERGENCY_ARRIVED,
  EN_TRASLADO: EventTypeLog.EMERGENCY_DURING_TRANSFER,
  FINALIZADA: EventTypeLog.EMERGENCY_FINALIZED,
  CANCELADA: EventTypeLog.EMERGENCY_CANCELED,
};
